config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cases

  root "cases#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  enum status: { waiting: 0, approved: 1, active: 2, complete: 3}
  validate :status_transition_allowed

  attr_accessor :user_id

  def transitionable_statuses(status)
    current = self.class.statuses[status]

    surroundings = [current - 1, current + 1]
      .select { |n| n.between?(0, self.class.statuses.length - 1)}

    self.class.statuses.select { |status, integer| surroundings.include?(integer)}
  end

  private
    def status_transition_allowed
      return if !status_changed?

      unless transitionable_statuses(status_was).include?(status)
        errors.add(:status, :invalid_transition, message: "status '#{status_was}' can only transition to: '#{transitionable_statuses(status_was).keys.join(",")}'")
      end
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, polymorphic: true
end

app/models/context.rb
# This class would probably correspond with "Bucket" in "On Writing Softare Well", 
#   meaning "relevant to various groupings of implicit event consumers,"
#   but I'm not sold on that word. I get it but it feels too extroardinary a term.
class Context < ApplicationRecord
  def record(recordable, options = {})
    recording = Recording.create context: self, creator: options[:creator]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :recordable, polymorphic: true
  belongs_to :recordable_previous, polymorphic: true
  belongs_to :context
  belongs_to :creator, class_name: "User"
end

app/models/recording.rb
# I'm not sure what the explanation of a recording is. I do, however, suspect
# it's meant to tie together multiple 'events' which might have occurred due 
# to a single action.

class Recording < ApplicationRecord
  belongs_to :context, touch: true
  belongs_to :creator, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, as: :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  include ContextScoped, SetRecordable

  def index
    @cases = Case.all
  end

  def edit
    @case = Case.find(params[:id])
  end

  def update
    set_user
    @case = @context.record updated_case, creator: @user

    respond_to do |format|
      format.any(:html, :js) { redirect_to edit_case_url(@case.id) }
    end
  end

  private

    def case_params
      params.require(:case).permit(:user_id, :name, :status, :content)
    end

    def set_user
      @user = User.find(case_params[:user_id])
    end

    def updated_case
      @recordable.attributes = case_params
      @recordable
    end
end

app/controllers/concerns/context_scoped.rb
module ContextScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_context
  end

  private
    def set_context
      @context = Context.all.sample
    end
end

app/controllers/concerns/set_recordable.rb
module SetRecordable
  extend ActiveSupport::Concern

  included do
    before_action :set_recordable
  end

  private
    def set_recordable
      #TODO(zemptime): infer recordable class from controller, or ask the controller and have it tell what this should be later
      @recordable = Case.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cases/edit.html.erb
<h1>Administering: <%= @case.name %></h1>
<p><%= link_to "back", cases_path %></p>

<%= form_for @case do |f| %>
  <% if @case.errors.any? %>
    <ul>
      <% @case.errors.each do |error| %>
        <li><%= error.message %></li>
      <% end%>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :status %>
  <%= f.select :status, options_for_select(Case.statuses.map {|k, v| [k.humanize.capitalize, k]}) %>
  <br />

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br />

  <%= f.label :user %>
  <%= f.select :user_id, options_for_select(User.all.map {|user| [user.name, user.id]}) %>
  <br />

  <%= f.submit %>
<% end %>

app/views/cases/index.html.erb
<h1>Cases</h1>

<ul>
  <% @cases.each do |c| %>
    <li>
      <%= link_to c.name, edit_case_path(c) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventSourcedNotifications</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>